### ISSUE TITLE
Getting first data and stop.

### ISSUE THREAD

**Issue by erolg** [RonB/angular-oboe#9] opened 2016-01-03 10:34 UTC
@RonB Hey many thanks for this service!

Firstly, It seems live stream JSON source no longer served.

```GET http://www.webbergen.nl/data/publicatie-website/largejson/contacts2.json 404 (Not Found)```

When i try to change it with my json source which is served every 2 second and do not stop.
I got just first data no more.. and status changing from reading to done. In other word "done" callback function triggered. I can't figure out which line cause the problem.

JSON object:
```
{
	"read": "2016-01-03T02:33:10.005941103+02:00",
	"precpu_stats": {
		"cpu_usage": {
			"total_usage": 0,
			"percpu_usage": null,
			"usage_in_kernelmode": 0,
			"usage_in_usermode": 0
		},
		"system_cpu_usage": 0,
		"throttling_data": {
			"periods": 0,
			"throttled_periods": 0,
			"throttled_time": 0
		}
	},
	"cpu_stats": {
		"cpu_usage": {
			"total_usage": 80251810,
			"percpu_usage": [5987016, 5120269, 11718861, 57425664],
			"usage_in_kernelmode": 0,
			"usage_in_usermode": 60000000
		},
		"system_cpu_usage": 46597080000000,
		"throttling_data": {
			"periods": 0,
			"throttled_periods": 0,
			"throttled_time": 0
		}
	},
	"memory_stats": {
		"usage": 3657728,
		"max_usage": 6344704,
		"stats": {
			"active_anon": 1630208,
			"active_file": 32768,
			"cache": 184320,
			"hierarchical_memory_limit": 9223372036854771712,
			"inactive_anon": 1843200,
			"inactive_file": 151552,
			"mapped_file": 151552,
			"pgfault": 2605,
			"pgmajfault": 3,
			"pgpgin": 2380,
			"pgpgout": 1487,
			"rss": 3473408,
			"rss_huge": 0,
			"total_active_anon": 1630208,
			"total_active_file": 32768,
			"total_cache": 184320,
			"total_inactive_anon": 1843200,
			"total_inactive_file": 151552,
			"total_mapped_file": 151552,
			"total_pgfault": 2605,
			"total_pgmajfault": 3,
			"total_pgpgin": 2380,
			"total_pgpgout": 1487,
			"total_rss": 3473408,
			"total_rss_huge": 0,
			"total_unevictable": 0,
			"total_writeback": 0,
			"unevictable": 0,
			"writeback": 0
		},
		"failcnt": 0,
		"limit": 3849080832
	},
	"blkio_stats": {
		"io_service_bytes_recursive": [{
			"major": 8,
			"minor": 0,
			"op": "Read",
			"value": 143360
		}, {
			"major": 8,
			"minor": 0,
			"op": "Write",
			"value": 0
		}, {
			"major": 8,
			"minor": 0,
			"op": "Sync",
			"value": 0
		}, {
			"major": 8,
			"minor": 0,
			"op": "Async",
			"value": 143360
		}, {
			"major": 8,
			"minor": 0,
			"op": "Total",
			"value": 143360
		}],
		"io_serviced_recursive": [{
			"major": 8,
			"minor": 0,
			"op": "Read",
			"value": 5
		}, {
			"major": 8,
			"minor": 0,
			"op": "Write",
			"value": 0
		}, {
			"major": 8,
			"minor": 0,
			"op": "Sync",
			"value": 0
		}, {
			"major": 8,
			"minor": 0,
			"op": "Async",
			"value": 5
		}, {
			"major": 8,
			"minor": 0,
			"op": "Total",
			"value": 5
		}],
		"io_queue_recursive": [],
		"io_service_time_recursive": [],
		"io_wait_time_recursive": [],
		"io_merged_recursive": [],
		"io_time_recursive": [],
		"sectors_recursive": []
	},
	"networks": {
		"eth0": {
			"rx_bytes": 28995,
			"rx_packets": 165,
			"rx_errors": 0,
			"rx_dropped": 12,
			"tx_bytes": 13197,
			"tx_packets": 166,
			"tx_errors": 0,
			"tx_dropped": 0
		}
	}
}
```

Controller: 

```
        .controller('StreamingCtrl', function($scope, Oboe) {
            $scope.offset = 0; // starting offset for virtual-scroll
            $scope.data = []; 
    
            Oboe({
                url: 'http://localhost:4243/containers/f78257b77b21/stats',
    
                pattern: 'read', 
                start: function(stream) {
                    // the stream starts. create a reference
                    $scope.stream = stream;
                    $scope.status = 'reading....';
                },
                done: function() {
                    $scope.status = 'done';
                }
            }).then(function() {
                // not used
            }, function(error) {
                // some error
            }, function(record) {
               $scope.data.push(record);
            });
        })
        .controller('NoStreamingCtrl', function($scope, $http) {
            $scope.offset = 0; // starting offset for virtual-scroll
            // the contacts read entirely before added to the scope
            $scope.contacts = [];
            $scope.status = 'reading....';
            $http.get('http://localhost:4243/containers/f78257b77b21/stats')
                    .success(function(response) {
                        $scope.contacts = response;
                        $scope.status = 'done';
                    });
        });
```
panel.html
```
       <div sf-scroller="y = 0 to data.length" ng-model="offset" class="scrollbar"></div>
        <div ng-repeat="d in data|filter:query|sublist:7:offset"
             ng-class-odd="'odd'" 
             ng-class-even="'even'" 
             class="grid-row">
            <div><strong>{{d}}</strong></div>
        </div>
```

**Comment by RonB** [comment] 2016-01-03 14:04
Hi Erol,

I have changed the url's for the large JSON so that they will be retrieved from Github instead of the former example website. Thank you for that.

Than, I think your problem is in the implementation of Oboe. If you look at https://github.com/jimhigson/oboe.js/issues/42 you see that after each object the done event is fired.

You might want to not close the stream on a done event but keep listening. Also check if the connection is stille open. If the connection is not closed but the done event is fired, than I can try to keep the stream open but I would need access to your json stream.

Please let me know if you would like to do that.

regards, 
Ronald

**Comment by erolg** [comment] 2016-01-03 14:54
Thanks Ronald, 

I understand, Done fires every json object's root closing..
My JSON stream is Docker Stats API from local daemon. So it is difficult because of my local network. Maybe we can use another sample API.

I'm trying to draw system resource charts with JSON stream API responses.
I think It will be better if I use WebSockets
Am I right?

**Comment by RonB** [comment] 2016-01-03 19:55
Hi Erol,

Correct. That is better suited technology if supported by your server. I recommend using angular-faye.
If you decide to go for that please close this issue.

Thanks

**Comment by erolg** [comment] 2016-01-03 20:02
Hey I rethink about this problem and If am i right, I can solve problem.

If I push received data to scope when done callback fire. With this approach can I solve my problem ?

I change my code but I think I missed sth.

```
.controller('StreamingCtrl', function($scope, Oboe) {
            $scope.offset = 0; // starting offset for virtual-scroll
            $scope.data = [];
          
            Oboe({
                url: 'http://localhost:4243/containers/f78257b77b21/stats',
                
                pattern: 'read', // all nodes that have an index property will be included
                start: function(stream) {
                    // thetream starts. create a reference
                    $scope.stream = stream;
                    $scope.status = 'reading....';
                },
                done: function(record) {
                        $scope.data.push(record);               
                }
            }).then(function() {
                // not used
            }, function(error) {
                // some error
            }, function() {
            });
        })
```

What do you think?

**Comment by RonB** [comment] 2016-01-04 13:23
Hi Erol,

You might try that, and see if the original stream is not closed after a certain timeout (use the chrome debugger). Please let me now if it works. I can add it to the documentation.

Good luck,
Ronald

**Closed by RonB** 2016-01-04 13:23 UTC

**Comment by erolg** [comment] 2016-01-04 16:15
Hi Ronanld,

When I run controller like that and log to console record value in done callback. Returned undefined from console for the record variable.

**Comment by RonB** [comment] 2016-01-09 10:18
Hi @erolg, I have fixed this issue in #10 . You need to use '!' as a pattern and a parameter in the done callback to receive each object.

**Comment by fredericojesus** [comment] 2016-01-24 19:24
@RonB the problem is in your done function, you can't resolve your promise (defer.resolve(parsedJSON);) every time the done is called, because in the controller if we wanted to make something after the stream had finished it would be impossible. Your promise should only be resolved in the end of the streaming.

In my point of view, the done callback should be used to modify data if needed, and then in the controller you should move your data in your notifyCallback and do something if needed in then when the stream has finished.

The defer.resolve state is wrong in your code I think :x what do you think ?

**Comment by RonB** [comment] 2016-01-26 18:08
@fredericojesus I don't think there is a problem in the code if you realize that the stream may not end at all. Oboe does not fire an event that the stream is closed, just the done event if an entire JSON object has been received.  The stream might remain open, it might not. The resolve is arbitrary but it is for the developer to deside whether or not to terminate the stream after the first done event.

I could remove the resolve but in the that case the promise will remain in memory forever. agree?
